spring:
  application:
    name: findex

  datasource:
    url: jdbc:postgresql://yamanote.proxy.rlwy.net:44055/railway
    username: postgres
    password: BRVEciPtrzlkJIDoasNSiGrUMMWZqHvL
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

openapi:
  service-key: bc8f6e4f29a518481711905f3b1ee6ae18e7a66a54b4ae8bd12531643e1fa59b