spring:
  application:
    name: findex

  datasource:
    url:
    username:
    password:
    driver-class-name:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

open-api:
  service-key:
  base-url: https://apis.data.go.kr/1160100/service/GetMarketIndexInfoService