spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  application:
    name: findex

  datasource:
    url: jdbc:h2:file:./data/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-h2.sql


open-api:
  service-key: ${OPEN_API_SERVICE_KEY}
  base-url: https://apis.data.go.kr/1160100/service/GetMarketIndexInfoService

scheduler:
  auto-sync:
    enabled: true
    cron: "0 0 0 * * *"